use_frameworks!

platform :ios, '10.0'

target 'LVSwiftKitModule_Example' do
  pod 'LVSwiftKitModule', :path => '../'

  target 'LVSwiftKitModule_Tests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 5.7.1'
    pod 'SnapKit', '~> 5.6.0'
  end
end
